---
title: "Grouping and quality checks"
author : "Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Load packages

```{r base}

# 1. Source functions ----

source("00_functions/graphical_par.R")
source("00_functions/theme_graph.R")

# 2. Required packages ----

library(tidyverse) # Core tidyverse packages
library(sf)

# 3. Set theme_graph() as the default ggplot theme ----

theme_set(theme_graph())

# 4. Load data ----

load("../data/09_gcrmndb_benthos.RData")

data_benthos <- synthetic_data %>% 
  filter(datasetID != "0009") # Remove XL Catlin Seaview Survey

rm(synthetic_data)

```

```{r}

# Number of sites ----

data_benthos %>% 
  select(decimalLongitude, decimalLatitude) %>%
  distinct() %>% 
  count() %>% 
  pull()

# Number of surveys ----

data_benthos %>% 
  select(decimalLongitude, decimalLatitude, year, month, eventDate) %>%
  distinct() %>% 
  count() %>% 
  pull()

# Number of individual datasets ----

data_benthos %>% 
  select(datasetID) %>%
  distinct() %>% 
  count() %>% 
  pull()

# First survey ----

data_benthos %>% 
  select(year) %>% 
  distinct() %>% 
  filter(year == min(year)) %>% 
  pull()

# Last survey ----

data_benthos %>% 
  select(year) %>% 
  distinct() %>% 
  filter(year == max(year)) %>% 
  pull()





indLastSurvey <- function(data){
  
  data %>% 
  select(year) %>% 
  distinct() %>% 
  filter(year == max(year)) %>% 
  pull()
  
}


data_benthos %>% 
  group_by(higherGeography) %>% 
  indLastSurvey()


```

```{r}

# 4. Percentage of surveys per year ----

data_benthic_surveys <- data_benthos %>% 
  group_by(decimalLongitude, decimalLatitude, year, eventDate) %>% 
  count() %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  mutate(percent = (n*100)/sum(n))

ggplot(data = data_benthic_surveys, aes(x = year, y = percent)) +
  geom_histogram(stat = "identity") +
  theme_graph()

```

# Map

```{r}

# 1. Define a CRS to center the map on 160° meridian line ----

crs_selected <- "+proj=eqc +lat_ts=0 +lat_0=0 +lon_0=160 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

# 2. Load data ----

# 2.1 Land data --

data_land <- st_read("../data/10_background-shp/ne_10m_land/ne_10m_land.shp") %>% 
  st_transform(crs = crs_selected)

# 2.2 Country boundaries data --

data_country <- st_read("../data/10_background-shp/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp") %>% 
  st_transform(crs = crs_selected)

# 2.3 EEZ --

# 2.3.1 Define the correction offset --

correction_offset <- 180 - 160 # Here 160 is the same value than +lon_0 from crs_selected

# 2.3.2 Define a long and slim polygon that overlaps the meridian line --

correction_polygon <- st_polygon(x = list(rbind(c(-0.0001 - correction_offset, 90),
                                                c(0 - correction_offset, 90),
                                                c(0 - correction_offset, -90),
                                                c(-0.0001 - correction_offset, -90),
                                                c(-0.0001 - correction_offset, 90)))) %>%
  st_sfc() %>%
  st_set_crs(4326)

# 2.3.3 Load and transform data --

data_eez <- st_read("../data/07_data-eez/eez_v11.shp") %>% 
  st_transform(crs = 4326) %>% 
  st_make_valid() %>% 
  st_difference(correction_polygon) %>% 
  st_transform(crs_selected)

# 3. Extract site coordinates ----

data_benthos_coords <- data_benthos %>% 
  select(decimalLatitude, decimalLongitude) %>% 
  distinct() %>% 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326) %>% 
  st_transform(crs = crs_selected)
  
# 4. Make the plot ----

ggplot() +
  geom_sf(data = data_eez, fill = NA, col = "lightgrey") +
  geom_sf(data = data_land) +
  geom_sf(data = data_country) +
  geom_sf(data = data_benthos_coords, alpha = 0.9, size = 0.75, col = "red") +
  # Graphical aspects
  coord_sf(ylim = c(-5000000, 5000000), expand = FALSE) +
  theme(text = element_text(family = font_choose_map),
        panel.border = element_rect(fill = NA, color = "black", linewidth = 1),
        axis.title = element_blank(),
        axis.text.x.top = element_text())

# 5. Save the plot ----

ggsave("../figs/map_sites.png", dpi = 600, width = 10, height = 3)

```

# Table of descriptors

## Per country

```{r}




```

## Per GCRMN region

```{r}




```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`